first =  Calendar.create(date: '20140623')
second = Calendar.create(date: '20140624')
third =  Calendar.create(date: '20140630')

first.matters.create( calendar_id: 1, department: "F201", case_number: "RIK2100001", petitioner: "KATHRYN HOLT", respondent: "HARVEY STEVENS", )
first.matters.create( calendar_id: 1, department: "F301", case_number: "RIK2100002", petitioner: "COURTNEY HOLLAND", respondent: "WENDELL PARKS" )
second.matters.create(calendar_id: 1, department: "F401", case_number: "RID2100003", petitioner: "PAM BLACK", respondent: "ANDREW FRANK" )
third.matters.create( calendar_id: 2, department: "F402", case_number: "RID2100004", petitioner: "BRETT HOWELL", respondent: "JOANNE PERKINS" )
third.matters.create( calendar_id: 3, department: "F201", case_number: "RID2100005", petitioner: "DUANE WOLFE", respondent: "MARIE HILL" )
third.matters.create( calendar_id: 3, department: "F301", case_number: "RID2100006", petitioner: "EDNA WADE", respondent: "WAYNE ANDERSON" )
