#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  username: <%= ENV['PG_USER'] %>
  password: "<%= ENV['PG_PASSWORD'] %>"
  database: triage_development

test:
  <<: *default
  username: <%= ENV['PG_USER'] %>
  password: "<%= ENV['PG_PASSWORD'] %>"
  database: triage_test

production:
  <<: *default
  username: "<%= ENV['PG_USER'] %>"
  password: "<%= ENV['PG_PASSWORD'] %>"
  database: triage_production
