#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  username: <%= ENV['PG_USER'] %>
  password: "<%= ENV['PG_PASSWORD'] %>"
  database: '<%= "#{File.basename(File.expand_path('../..', __FILE__))}_development" %>'

test:
  <<: *default
  username: <%= ENV['PG_USER'] %>
  password: "<%= ENV['PG_PASSWORD'] %>"
  database: '<%= "#{File.basename(File.expand_path('../..', __FILE__))}_test" %>'

production:
  <<: *default
  username: "<%= ENV['PG_USER'] %>"
  password: "<%= ENV['PG_PASSWORD'] %>"
  database: '<%= "#{File.basename(File.expand_path('../..', __FILE__))}_production" %>'
