source 'https://rubygems.org'

gem 'rails', '4.1.1'
gem 'active_model_serializers', '0.8.1'
gem 'daemon', '1.1.0'
gem 'delayed_job_active_record', '4.0.1'
gem 'friendly_id', '5.0.4'
gem 'nokogiri', '1.6.2.1'
gem 'pg', '0.17.1'
gem 'pry', '0.9.12.6'
gem 'sdoc', '~> 0.4.0',          group: :doc
gem 'spring',        group: :development
gem 'thin'
gem 'typhoeus', '0.6.9'

group :development do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'pry-rails', '0.3.2'
end

group :development, :test do
  gem 'database_cleaner', '1.2.0'
  gem 'guard-rspec', '4.2.10'
  gem 'rb-fsevent' if `uname` =~ /Darwin/
  gem 'rspec-mocks', '2.14.6'
  gem 'rspec-rails', '2.14.2'
  gem 'spring-commands-rspec', '1.0.2'
  gem 'vcr', '2.9.0'
end

group :test do
end

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# Use debugger
# gem 'debugger', group: [:development, :test]

