source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.1.1'
# Use postgresql as the database for Active Record
gem 'pg', '0.17.1'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0',          group: :doc

# Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
gem 'spring',        group: :development

gem 'active_model_serializers', '0.8.1'
gem 'friendly_id', '5.0.4'
gem 'nokogiri', '1.6.2.1'

group :development do
  gem 'better_errors'
  gem 'binding_of_caller'
end

group :development, :test do
  gem 'database_cleaner', '1.2.0'
  gem 'guard-rspec', '4.2.10'
  gem 'rb-fsevent' if `uname` =~ /Darwin/
  gem 'rspec-mocks', '2.14.6'
  gem 'rspec-rails', '2.14.2'
  gem 'spring-commands-rspec', '1.0.2'
end

group :test do
  gem 'vcr', '2.9.0'
  gem 'webmock', '1.17.4'
end

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# Use debugger
# gem 'debugger', group: [:development, :test]

